name: Pipeline

on:
  push:
    branches:
      - main
    paths:
      - prject/**

jobs:
  pre-build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11"]
    runs-on: ${{ matrix.platform }}
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      # Install python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      # Dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      # Check lints
      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')
